const data = [{
    id: 1,
    category: 1,
    categoryName: 'Man Section',
    name: 'Nike Revolution',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 49.99,
    img: '/img/products/ssh-0001.png',
    stock: 10,
    promo: true,
    off: '20%'
  },
  {
    id: 2,
    category: 1,
    categoryName: 'Man Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 100.25,
    img: '/img/products/ssh-0002.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 3,
    category: 1,
    categoryName: 'Man Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 49.99,
    img: '/img/products/ssh-0003.png',
    stock: 10,
    promo: false,
    off: ''
  }, {
    id: 4,
    category: 1,
    categoryName: 'Man Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 59.99,
    img: '/img/products/ssh-0004.png',
    stock: 10,
    promo: true,
    off: '15%'
  },
  {
    id: 5,
    category: 1,
    categoryName: 'Man Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 49.99,
    img: '/img/products/ssh-0005.png',
    stock: 10,
    promo: true,
    off: '10%'
  },
  {
    id: 6,
    category: 1,
    categoryName: 'Man Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 40.00,
    img: '/img/products/ssh-0006.png',
    stock: 10,
    promo: true,
    off: '5%'
  },
  {
    id: 7,
    category: 1,
    categoryName: 'Man Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 49.99,
    img: '/img/products/ssh-0007.png',
    stock: 10,
    promo: true,
    off: '10%'
  },
  {
    id: 8,
    category: 1,
    categoryName: 'Man Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0008.png',
    stock: 10,
    promo: true,
    off: '16%'
  },
  {
    id: 9,
    category: 2,
    categoryName: 'Woam Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0009.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 10,
    category: 1,
    categoryName: 'Man Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0009.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 11,
    category: 1,
    categoryName: 'Man Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0009.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 12,
    category: 2,
    categoryName: 'Woam Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0010.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 13,
    category: 2,
    categoryName: 'Woam Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0011.png',
    stock: 10,
    promo: true,
    off: '15%'
  },
  {
    id: 14,
    category: 2,
    categoryName: 'Woam Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0012.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 15,
    category: 2,
    categoryName: 'Woam Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0013.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 16,
    category: 2,
    categoryName: 'Woam Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0014.png',
    stock: 10,
    promo: true,
    off: '20%'
  },
  {
    id: 17,
    category: 2,
    categoryName: 'Woam Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0015.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 18,
    category: 2,
    categoryName: 'Woam Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0015.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 19,
    category: 2,
    categoryName: 'Woam Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0015.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 20,
    category: 2,
    categoryName: 'Woam Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0015.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 21,
    category: 3,
    categoryName: 'Kids Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0000.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 22,
    category: 3,
    categoryName: 'Kids Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0000.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 23,
    category: 3,
    categoryName: 'Kids Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0000.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 24,
    category: 3,
    categoryName: 'Kids Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0000.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 25,
    category: 3,
    categoryName: 'Kids Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0000.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 26,
    category: 3,
    categoryName: 'Kids Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0000.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 27,
    category: 3,
    categoryName: 'Kids Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0000.png',
    stock: 10,
    promo: false,
    off: ''
  },
  {
    id: 28,
    category: 3,
    categoryName: 'Kids Section',
    name: 'Lorem',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    price: 35.99,
    img: '/img/products/ssh-0000.png',
    stock: 10,
    promo: false,
    off: ''
  }


];

export default data